### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by chrislojacono** [nss-evening-cohort-13/renaissance-fair-dashboard-renaissance-fair-dashboard#73]
# User Story
We should have a wireframe that shows how the events page should look and how the graph and form should appear
# Link
[Wireframe](https://www.figma.com/file/dVczHuXR4uxTSJ9eqCel4l/Freelancer-Wireframe?node-id=0%3A1)
# Acceptance Criteria
Should be easy to understand and show the flow of the website
Should also use Figma

# Dependencies
N/A

# Dev Notes
- [x] wireframe complete

**Comment by kaitvan** [comment]
https://www.figma.com/file/dVczHuXR4uxTSJ9eqCel4l/Freelancer-Wireframe?node-id=0%3A1
